---
name: ⏰ Scheduled Container Scan

on:
  schedule:
    - cron: "0 9 * * 1-5" # Every weekday at 9AM UTC
  workflow_dispatch:

permissions: {}

jobs:
  scheduled-container-scan:
    name: Scheduled Container Scan
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scheduled-container-scan.yml@9fbe4cbba23d4a768eb36462458a4cfcb63682e1 # v5.2.0
    secrets:
      cve-scan-slack-webhook-url: ${{ secrets.ANALYTICAL_PLATFORM_CVE_SCAN_SLACK_WEBHOOK_URL }}
