---
name: ⏰ Scheduled Container Scan

on:
  schedule:
    - cron: "0 7 * * 1-5" # Every weekday at 7AM UTC
  workflow_dispatch:

permissions: {}

jobs:
  scheduled-container-scan:
    name: Scheduled Container Scan
    permissions:
      contents: read
      security-events: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scheduled-container-scan.yml@handle_empty_rules # v7.0.0
    with:
      runtime: python
    secrets:
      cve-scan-slack-webhook-url: ${{ secrets.ANALYTICAL_PLATFORM_CVE_SCAN_SLACK_WEBHOOK_URL }}
